---

- name: Copy Wordpress Nginx
  template:
   src: templates/wordpress.conf
   dest: /etc/nginx/conf.d/

#- name: check conf
#  command: nginx -t
#  register: check_conf

- name: permission
  file:
   path: /var/www/html/
   state: directory
   owner: nginx

- name: restart nginx to apply conf
  service:
   name: nginx
   state: restarted
#  when: check_conf.rc == "0"
