---
#- name: Get Password
#  raw: "grep 'temporary password' /var/log/mysqld.log | awk '{print $13}'"
#  register: password

- name: Create Wordpress User
  mysql_user:
     login_user: root
     login_password: t4p1S|asuli
     login_unix_socket: /var/lib/mysql/mysql.sock
     name: wordpress
     password: wordpress
     priv: 'wordpress.*:ALL'
     state: present

